
package at.gv.brz.training.krachbum.bom;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZeitverwaltungService", targetNamespace = "http://bom.krachbum.training.brz.gv.at/", wsdlLocation = "http://localhost:8080/WS/Zeitverwaltung?wsdl")
public class ZeitverwaltungService
    extends Service
{

    private final static URL ZEITVERWALTUNGSERVICE_WSDL_LOCATION;
    private final static WebServiceException ZEITVERWALTUNGSERVICE_EXCEPTION;
    private final static QName ZEITVERWALTUNGSERVICE_QNAME = new QName("http://bom.krachbum.training.brz.gv.at/", "ZeitverwaltungService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WS/Zeitverwaltung?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZEITVERWALTUNGSERVICE_WSDL_LOCATION = url;
        ZEITVERWALTUNGSERVICE_EXCEPTION = e;
    }

    public ZeitverwaltungService() {
        super(__getWsdlLocation(), ZEITVERWALTUNGSERVICE_QNAME);
    }

    public ZeitverwaltungService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZEITVERWALTUNGSERVICE_QNAME, features);
    }

    public ZeitverwaltungService(URL wsdlLocation) {
        super(wsdlLocation, ZEITVERWALTUNGSERVICE_QNAME);
    }

    public ZeitverwaltungService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZEITVERWALTUNGSERVICE_QNAME, features);
    }

    public ZeitverwaltungService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZeitverwaltungService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IZeitverwaltung
     */
    @WebEndpoint(name = "ZeitverwaltungPort")
    public IZeitverwaltung getZeitverwaltungPort() {
        return super.getPort(new QName("http://bom.krachbum.training.brz.gv.at/", "ZeitverwaltungPort"), IZeitverwaltung.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IZeitverwaltung
     */
    @WebEndpoint(name = "ZeitverwaltungPort")
    public IZeitverwaltung getZeitverwaltungPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://bom.krachbum.training.brz.gv.at/", "ZeitverwaltungPort"), IZeitverwaltung.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZEITVERWALTUNGSERVICE_EXCEPTION!= null) {
            throw ZEITVERWALTUNGSERVICE_EXCEPTION;
        }
        return ZEITVERWALTUNGSERVICE_WSDL_LOCATION;
    }

}
