
package at.gv.brz.trainig.krachbum.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import at.gv.brz.trainig.krachbum.server.interfaces.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Mathe", targetNamespace = "http://interfaces.server.krachbum.trainig.brz.gv.at/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Mathe {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addiere", targetNamespace = "http://interfaces.server.krachbum.trainig.brz.gv.at/", className = "at.gv.brz.trainig.krachbum.server.interfaces.Addiere")
    @ResponseWrapper(localName = "addiereResponse", targetNamespace = "http://interfaces.server.krachbum.trainig.brz.gv.at/", className = "at.gv.brz.trainig.krachbum.server.interfaces.AddiereResponse")
    @Action(input = "http://interfaces.server.krachbum.trainig.brz.gv.at/Mathe/addiereRequest", output = "http://interfaces.server.krachbum.trainig.brz.gv.at/Mathe/addiereResponse")
    public int addiere(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
